name: Generate Snake Animation 🐍

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create dist folder
        run: mkdir -p dist

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Lucasapn2
          outputs: |
            dist/snake.svg
          color_snake: '#9400D3'       # Roxo (igual o que aparece na sua imagem)
          color_dots: '#CCCCCC'        # Cinza claro
          color_background: '#000000'  # Fundo preto

