name: Generate Snake Animation 🐍

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite (UTC)
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create dist folder
        run: mkdir -p dist

      - name: Generate Snake SVGs (light and dark)
        uses: Platane/snk@v3
        with:
          github_user_name: Lucasapn2
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
          color_snake: '#9400D3'
          color_dots: '#CCCCCC,#8dbdff,#64a1f4,#4b91f1,#3c7dd9'

      - name: Push Snake SVGs to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
